In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7616, 8736, 5269, 3902],
 [7616, 8736, 5269, 5876],
 [7616, 8513, 5269, 491],
 [6597, 229, 9734, 4325, 5148],
 [6597, 229, 9734, 4325, 8128],
 [2107, 7616, 640, 5269, 3411],
 [5756, 3602, 9180, 4325]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7616 8736 5269 3902]
 [   0    0    0    0 7616 8736 5269 5876]
 [   0    0    0    0 7616 8513 5269  491]
 [   0    0    0 6597  229 9734 4325 5148]
 [   0    0    0 6597  229 9734 4325 8128]
 [   0    0    0 2107 7616  640 5269 3411]
 [   0    0    0    0 5756 3602 9180 4325]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 173ms/step


array([[[-0.01668034, -0.01775302,  0.01033009,  0.01361645,
         -0.01910811, -0.01593982,  0.00164754, -0.00732354,
          0.0227697 , -0.04332608],
        [-0.01668034, -0.01775302,  0.01033009,  0.01361645,
         -0.01910811, -0.01593982,  0.00164754, -0.00732354,
          0.0227697 , -0.04332608],
        [-0.01668034, -0.01775302,  0.01033009,  0.01361645,
         -0.01910811, -0.01593982,  0.00164754, -0.00732354,
          0.0227697 , -0.04332608],
        [-0.01668034, -0.01775302,  0.01033009,  0.01361645,
         -0.01910811, -0.01593982,  0.00164754, -0.00732354,
          0.0227697 , -0.04332608],
        [-0.00208724,  0.0315646 ,  0.00393114,  0.03779144,
         -0.01141015,  0.02679772,  0.0390428 ,  0.00041938,
         -0.01310871, -0.01327498],
        [ 0.01315638, -0.03059037, -0.04091934,  0.00985619,
         -0.00201106,  0.00914408,  0.03275866,  0.00244331,
          0.04360114,  0.02115016],
        [ 0.02909805,  0.02093292, -0.02122935,  0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 7616, 8736, 5269, 3902])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 85ms/step


array([[-0.01668034, -0.01775302,  0.01033009,  0.01361645, -0.01910811,
        -0.01593982,  0.00164754, -0.00732354,  0.0227697 , -0.04332608],
       [-0.01668034, -0.01775302,  0.01033009,  0.01361645, -0.01910811,
        -0.01593982,  0.00164754, -0.00732354,  0.0227697 , -0.04332608],
       [-0.01668034, -0.01775302,  0.01033009,  0.01361645, -0.01910811,
        -0.01593982,  0.00164754, -0.00732354,  0.0227697 , -0.04332608],
       [-0.01668034, -0.01775302,  0.01033009,  0.01361645, -0.01910811,
        -0.01593982,  0.00164754, -0.00732354,  0.0227697 , -0.04332608],
       [-0.00208724,  0.0315646 ,  0.00393114,  0.03779144, -0.01141015,
         0.02679772,  0.0390428 ,  0.00041938, -0.01310871, -0.01327498],
       [ 0.01315638, -0.03059037, -0.04091934,  0.00985619, -0.00201106,
         0.00914408,  0.03275866,  0.00244331,  0.04360114,  0.02115016],
       [ 0.02909805,  0.02093292, -0.02122935,  0.04038859, -0.01450393,
        -0.00799016, -0.03210871, -0.01238375